server:
  port: 8092
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cms?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 5000
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    check-template-location: true
    mode: HTML5

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.roots.cms.entity

qqwry:
  dat:
    path: src\main\resources\ip\qqwry.dat